# Generated by Django 4.1.7 on 2023-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=25)),
                ("CPassword", models.CharField(max_length=25)),
            ],
        ),
    ]
