# Generated by Django 4.1.7 on 2023-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0002_register"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="first",
            field=models.BooleanField(default=False, verbose_name="first"),
        ),
        migrations.AddField(
            model_name="register",
            name="second",
            field=models.BooleanField(default=False, verbose_name="second"),
        ),
    ]
