# Generated by Django 4.1.7 on 2023-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0003_register_first_register_second"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="first",
            field=models.BooleanField(
                default=False,
                verbose_name="I consent to Herboil processing my personal data in order to send personalized marketing material in accordance with the consent form and the privacy policy.",
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="second",
            field=models.BooleanField(
                default=False,
                verbose_name='By clicking "create account", I consent to the privacy policy.',
            ),
        ),
    ]
