# Generated by Django 4.1.7 on 2023-04-03 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0004_alter_register_first_alter_register_second"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="first",
        ),
        migrations.RemoveField(
            model_name="register",
            name="second",
        ),
    ]
