# Generated by Django 4.1.7 on 2023-04-04 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0005_remove_register_first_remove_register_second"),
    ]

    operations = [
        migrations.DeleteModel(
            name="register",
        ),
    ]
